embeddings {
  tensor_name: "embedding:0"
  metadata_path: "D:/develop/workstations/pycharm_projects/TensorFlow_tutorials/my_TensorFlow_demos/Visual_test/projector/projector/metadata.tsv"
  sprite {
    image_path: "D:/develop/workstations/pycharm_projects/TensorFlow_tutorials/my_TensorFlow_demos/Visual_test/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
